# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: wget -q https://storage.googleapis.com/golang/go1.15.linux-amd64.tar.gz
      - run: sudo rm -rf /usr/local/go
      - run: sudo tar -C /usr/local -xzf go1.15.linux-amd64.tar.gz

      - run: sudo -E /usr/local/go/bin/go test -v -cover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)


  checks:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: .circleci/build-cmds
      - run: .circleci/gofmt

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - checks
